// Exact color palette, shadows, and radii from the web prototype
export const theme = {
  colors: {
    bg: '#F7F2EA',
    bgSoft: '#FBF7F0',
    cream: '#FFF9EF',
    sage: '#DDEDDC',
    mint: '#DFF2EC',
    lavender: '#E8DDFB',
    lavenderStrong: '#9D7BEA',
    peach: '#F8DCCB',
    rose: '#F4C7D2',
    sun: '#F7D875',
    aqua: '#9FD9D0',
    teal: '#16A7A0',
    ink: '#1F2130',
    muted: '#7A7C8C',
    softMuted: '#A7A1A0',
    white: '#FFFFFF',
  },
  gradients: {
    primary: ['#8B72CF', '#16A7A0'] as const,
    hero: ['#E7DDFC', '#DCF0E3', '#F8DCCB'] as const,
    love: ['#F4C7D2', '#E8DDFB', '#DDEDDC'] as const,
    compatibility: ['#DDEDDC', '#E8DDFB', '#F8DCCB'] as const,
    firstMirror: ['#E7DDFC', '#DCF0E3', '#F8DCCB'] as const,
    emotional: ['#F8DCCB', '#F7D875'] as const,
    lovePattern: ['#F4C7D2', '#E8DDFB'] as const,
    shadow: ['#E8DDFB', '#DDEDDC'] as const,
    career: ['#DDEDDC', '#DFF2EC'] as const,
    growth: ['#F7D875', '#F8DCCB'] as const,
    theme12: ['#9FD9D0', '#DDEDDC'] as const,
    decodeLove: ['#F4C7D2', '#E8DDFB'] as const,
    decodeCompatibility: ['#DDEDDC', '#DFF2EC'] as const,
    decodeSoulprint: ['#E8DDFB', '#F8DCCB'] as const,
    profileGradient: ['#16A7A0', '#8EDBD0'] as const,
    streak: ['rgba(247,216,117,0.3)', 'rgba(248,220,203,0.3)'] as const,
  },
  shadows: {
    warm: {
      shadowColor: 'rgba(99, 82, 60, 0.14)',
      shadowOffset: { width: 0, height: 22 },
      shadowRadius: 60,
      shadowOpacity: 1,
      elevation: 12,
    },
    warmSoft: {
      shadowColor: 'rgba(99, 82, 60, 0.09)',
      shadowOffset: { width: 0, height: 12 },
      shadowRadius: 30,
      shadowOpacity: 1,
      elevation: 8,
    },
    warmSm: {
      shadowColor: 'rgba(99, 82, 60, 0.05)',
      shadowOffset: { width: 0, height: 8 },
      shadowRadius: 18,
      shadowOpacity: 1,
      elevation: 4,
    },
    primaryGlow: {
      shadowColor: 'rgba(139,114,207,0.22)',
      shadowOffset: { width: 0, height: 14 },
      shadowRadius: 30,
      shadowOpacity: 1,
      elevation: 6,
    },
    tealGlow: {
      shadowColor: 'rgba(22,167,160,0.22)',
      shadowOffset: { width: 0, height: 12 },
      shadowRadius: 28,
      shadowOpacity: 1,
      elevation: 6,
    },
  } as Record<string, any>,
  radius: {
    xl: 34,
    lg: 28,
    md: 22,
    sm: 16,
    xs: 14,
    full: 9999,
  },
  fonts: {
    serif: 'Georgia' as const,
    sans: 'Inter' as const,
  },
};

export type Theme = typeof theme;
